# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [4]:
print(a.sum()) 
print(np.sum(a))
print(sum(a))

300
300
300


In [ ]:
三者是相同的結果
但在使用上，np.sum(a)則不會對原本的陣列進行影響

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [6]:
A = np.random.random((5, 5))
A
Amin,Amax = A.min(), A.max()
print(Amin)
print(Amax)

0.051822797495904016
0.9981665309047238


In [7]:
A - Amin / Amax - Amin

array([[ 0.64816253,  0.79362788,  0.6754775 ,  0.04045657, -0.00725887],
       [ 0.05204862,  0.0979429 ,  0.68908031,  0.41801961,  0.22085538],
       [ 0.40774319,  0.15745567,  0.64253074, -0.05191799,  0.65923625],
       [ 0.25608763,  0.29479664,  0.89442575,  0.82959843,  0.57552188],
       [ 0.66879949,  0.52413735,  0.37110551,  0.41409145,  0.04073357]])

In [ ]:

'''
Your Code
'''

array([[0.13197583, 0.1034873 , 0.        , 0.31390653, 0.35846645],
       [0.14777047, 0.28417508, 0.75999011, 0.29030305, 0.72055306],
       [0.98492508, 0.41249799, 1.        , 0.39756699, 0.39109584],
       [0.85537752, 0.84696945, 0.69635415, 0.86720675, 0.61212718],
       [0.24295928, 0.99120832, 0.09074347, 0.78251208, 0.57787873]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [20]:
randint(100,size=10)
a

array([ 9, 67, 71, 68, 38, 96, 55, 56, 38, 99])

In [21]:
amax = a.max()
np.where(a == amax, -1, a)

array([ 9, 67, 71, 68, 38, 96, 55, 56, 38, -1])

In [24]:
b = np.random.random((1, 10))*100
print(b)
bmax = b.max()
np.where(b == bmax, -1, b)

[[64.97069176 73.12457252 87.38897329 40.03362832 58.33092227 25.22738242
  28.23975071 96.69491684 50.66991403 21.7748108 ]]


array([[64.97069176, 73.12457252, 87.38897329, 40.03362832, 58.33092227,
        25.22738242, 28.23975071, -1.        , 50.66991403, 21.7748108 ]])