# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[2, 3, 8, ..., 4, 7, 5],
        [6, 6, 4, ..., 1, 3, 4],
        [4, 0, 2, ..., 8, 2, 3],
        ...,
        [9, 2, 0, ..., 4, 7, 8],
        [8, 6, 8, ..., 2, 5, 8],
        [3, 9, 6, ..., 2, 5, 0]],

       [[6, 4, 1, ..., 1, 9, 8],
        [5, 8, 9, ..., 8, 1, 0],
        [7, 3, 9, ..., 6, 9, 6],
        ...,
        [0, 8, 5, ..., 9, 2, 8],
        [0, 3, 5, ..., 8, 0, 2],
        [7, 9, 5, ..., 6, 5, 1]],

       [[7, 1, 1, ..., 6, 4, 3],
        [3, 6, 6, ..., 8, 9, 8],
        [8, 7, 7, ..., 7, 6, 3],
        ...,
        [0, 9, 8, ..., 0, 1, 2],
        [4, 7, 7, ..., 1, 5, 3],
        [5, 0, 2, ..., 4, 8, 9]],

       ...,

       [[6, 4, 4, ..., 0, 7, 9],
        [2, 7, 7, ..., 3, 5, 4],
        [2, 3, 6, ..., 0, 9, 9],
        ...,
        [5, 9, 4, ..., 6, 4, 8],
        [2, 0, 5, ..., 6, 2, 5],
        [5, 5, 5, ..., 8, 9, 8]],

       [[6, 0, 8, ..., 3, 3, 5],
        [1, 6, 6, ..., 3, 3, 3],
        [1, 8, 2, ..., 4, 5, 9],
        ...,
        [6, 0, 3, ..., 

In [11]:
%timeit -n 10 a = 2

for row in Z:
    for d in row:
        next_d = d+1

58.7 ns ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit -n 10 a = 2

for d in Z.flat:
    next_d = d+1

64.5 ns ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit -n 10 a = 2

for d in np.nditer(Z):
    next_d = d+1

64.5 ns ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [19]:

Z = np.random.randint(0,10,50)
print(Z)


[1 5 0 9 7 7 2 9 6 3 3 1 9 6 9 4 0 0 1 3 5 4 9 1 5 9 9 5 4 1 5 5 3 2 9 0 2
 8 3 4 0 0 0 8 1 2 3 3 8 3]


In [31]:
counts = np.bincount(Z)
print(np.argmax(counts))
print(counts)
print(np.where(Z == np.argmax(counts)))

3
[7 6 4 8 4 6 2 2 3 8]
(array([ 9, 10, 19, 32, 38, 46, 47, 49], dtype=int32),)


bincount:<br>
Count number of occurrences of each value in array of non-negative ints.
它會回傳陣列裡，min~max之間的數值，當作index，並列出各數值的出現頻率

In [13]:
'''
Your Code
'''

array([ 0,  5,  9, 10, 11, 12, 18, 22, 38, 39, 41, 47, 49])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [32]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[0, 6, 9, 0, 9, 0]
[0, 6, 9, 0, 9, 0]
[[2, 4, 8, 5], [0, 3, 1, 3], [6, 7, 9, 3]]
[array([2, 4, 8, 5]), array([0, 3, 1, 3]), array([6, 7, 9, 3])]
[[[7, 3], [5, 6], [1, 4]], [[0, 3], [9, 8], [7, 4]]]
[array([[7, 3],
       [5, 6],
       [1, 4]]), array([[0, 3],
       [9, 8],
       [7, 4]])]


In [ ]:
'''
Your Code
'''